sudo: false
language: node_js
node_js:
  - stable
before_install:
- npm update
install:
  - npm install
script:
  - npx commitlint --from=HEAD~1
  - npm run lint
  - npm run test:coverage
after_success:
  - npm run coveralls
branches:
  only:
  - master
cache:
  directories:
    - node_modules
notifications:
  email: false